/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\models\pokedex.glb .\src\components\Pokedex\PokedexModel\ 
Author: aidanwolf (https://sketchfab.com/aidanwolf)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pokedex-0ec4ebddf61149829c7a3031451290f1
Title: Pokédex
*/

import { Decal, useGLTF, useTexture } from '@react-three/drei';
import { motion } from 'framer-motion-3d';
import { CanvasTexture } from 'three';
import TextToTexture from '../../../helpers/TextToTextureHelper';

function PokedexModel(props) {
  const degree = Math.PI/180;
  const { nodes, materials } = useGLTF('models/pokedex.glb');
  const texture = useTexture('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png');
  texture.minFilter = 1003; // NearestFilter for pixelated view
  texture.magFilter = 1003;

  //const c = document.createElement('canvas');
  //c.width = 256;
  //c.height = 128;
  //let ctx = c.getContext('2d');
  //if (ctx !== null && ctx !== void 0) {
  //  ctx.fillStyle = "rbga(255, 255, 255, 0)";
  //  ctx.fillRect(0, 0, c.width, c.height);
  //  ctx.textAlign = "center";
  //  ctx.textBaseline = "middle";
  //  ctx.fillStyle = "magenta";
  //  ctx.font = "bold 36px Arial";
  //  let text = "I love Three.js";
  //  ctx.fillText(text, c.width * 0.5, c.height * 0.5);
  //  ctx.strokeStyle = "red";
  //  ctx.strokeText(text, c.width * 0.5, c.height * 0.5);
  //}


  const textText = TextToTexture(['Pikachu', 'yte'], 256, 128, 36, 0, 0);
  const abilitiesTexture = TextToTexture([`asdas: ${'asdggfas'}`], 256, 96, 24, 0, 48);
  const statsLeftTexture = TextToTexture([`HP: ${123}`], 256, 96, 24, 0, 48);
  const statsRightTexture = TextToTexture([`Attack: ${123}`], 256, 128, 24, 0, 48);

  return (
    <group {...props} dispose={null} rotation={[-Math.PI, -1.55, -Math.PI]}>
      <group scale={[0.129, 1.202, 0.129]}>
        <motion.mesh initial={{rotateY: -150*degree}} animate={{rotateY: 30*degree}} transition={{duration: 0.5}} >
          <group rotation={[-Math.PI, 30*degree, -Math.PI]}>
            <mesh geometry={nodes.Object_17.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.material_2} >
              <Decal
                position={[0.5, 0.175, 5.51]}
                rotation={[0, 90*degree, 0]}
                scale={[-6.53, 0.245, 2]}>
                  <meshBasicMaterial map={abilitiesTexture} polygonOffset polygonOffsetFactor={-1}/>
              </Decal>
            </mesh>
            <mesh geometry={nodes.Object_18.geometry} material={materials.material_2} >
              <Decal
                position={[0.5, -0.652, 3.63]}
                rotation={[0, 90*degree, 0]}
                scale={[-2.92, 0.116, 2]}>
                  <meshBasicMaterial map={statsLeftTexture} polygonOffset polygonOffsetFactor={-1}/>
              </Decal>
            </mesh>
            <mesh geometry={nodes.Object_18.geometry} material={materials.material_2} >
              <Decal
                position={[0.5, -0.652, 7.37]}
                rotation={[0, 90*degree, 0]}
                scale={[-2.92, 0.116, 2]}>
                  <meshBasicMaterial map={statsRightTexture} polygonOffset polygonOffsetFactor={-1}/>
              </Decal>
            </mesh>
            <mesh geometry={nodes.Object_19.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.Black} />
            <mesh geometry={nodes.Object_21.geometry} material={materials['White.001']} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.LightYellow} />
            <mesh geometry={nodes.Object_23.geometry} material={materials.Yellow} />
            <mesh geometry={nodes.Object_24.geometry} material={materials.Metal} />
          </group>
        </motion.mesh>
        <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.White} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_2} >
          <Decal
            position={[0.5, 0.05, 5]}
            rotation={[0, 90*degree, 0]}
            scale={[3.5, 0.45, 2]}>
              <meshBasicMaterial map={texture} polygonOffset polygonOffsetFactor={-1}/>
          </Decal>
        </mesh>
        <mesh geometry={nodes.Object_7.geometry} material={materials.LCD2} >
          <Decal
            position={[0.5, -0.553, 6.37]}
            rotation={[0, 90*degree, 0]}
            scale={[2.85, 0.19, 2]}>
              <meshBasicMaterial map={textText} polygonOffset polygonOffsetFactor={-1}/>
          </Decal>
        </mesh>
        <mesh geometry={nodes.Object_8.geometry} material={materials.LightRed} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.LightYellow} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.LightGreen} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Lens} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Pinkish} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Blue} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Dark} />
      </group>
    </group>
  )
}

useGLTF.preload('models/pokedex.glb')

export default PokedexModel
